apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: relations-sink
objects:
  - apiVersion: v1
    stringData:
      relations-api.authn.client.issuer: "https://fake_idp/"
      relations-api.authn.client.id: "fake-sa"
      relations-api.authn.client.secret: "fake_secret"
    kind: Secret
    metadata:
      name: relations-sink-config
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaConnector
    metadata:
      name: relations-sink-connector
      labels:
        strimzi.io/cluster: ${ENV_NAME}
    spec:
      class: org.project_kessel.kafka.relations.sink.RelationsSinkConnector
      tasksMax: 1
      config:
        topics: "outbox.event.relations-replication-event"
        relations-api.target-url: ${RELATIONS_API_URL}
        relations-api.is-secure-clients: false
        relations-api.authn.mode: "disabled"
        relations-api.authn.client.issuer: ${secrets:relations-sink-config:relations-api.authn.client.issuer}
        relations-api.authn.client.id: ${secrets:relations-sink-config:relations-api.authn.client.id}
        relations-api.authn.client.secret: ${secrets:relations-sink-config:relations-api.authn.client.secret}
parameters:
  - description: ClowdEnvironment name (ephemeral, stage, prod)
    name: ENV_NAME
    required: true
  - description: Address of the relations api service
    name: RELATIONS_API_URL
    value: "kessel-relations-api:9000"
    required: true
